CREATE TYPE "public"."attribute" AS ENUM('DARK', 'DIVINE', 'EARTH', 'FIRE', 'LIGHT', 'WATER', 'WIND');--> statement-breakpoint
CREATE TYPE "public"."rarity" AS ENUM('COMMON', 'RARE', 'SUPER RARE', 'ULTRA RARE');--> statement-breakpoint
CREATE TABLE "products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(60) NOT NULL,
	"price" integer NOT NULL,
	"imageUrl" varchar(255) NOT NULL,
	"rarity" "rarity" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventories" (
	"userName" varchar(30) NOT NULL,
	"cardId" integer NOT NULL,
	"creationDate" timestamp DEFAULT now() NOT NULL,
	"value" integer NOT NULL,
	CONSTRAINT "inventories_userName_cardId_pk" PRIMARY KEY("userName","cardId")
);
--> statement-breakpoint
CREATE TABLE "pack_cards" (
	"cardId" integer NOT NULL,
	"packId" integer NOT NULL,
	CONSTRAINT "pack_cards_cardId_packId_pk" PRIMARY KEY("cardId","packId")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"name" varchar(30) PRIMARY KEY NOT NULL,
	"passwordHash" varchar(100) NOT NULL,
	"isAdmin" boolean DEFAULT false NOT NULL,
	"yugiPesos" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "inventories" ADD CONSTRAINT "inventories_userName_users_name_fk" FOREIGN KEY ("userName") REFERENCES "public"."users"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventories" ADD CONSTRAINT "inventories_cardId_products_id_fk" FOREIGN KEY ("cardId") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_cards" ADD CONSTRAINT "pack_cards_cardId_products_id_fk" FOREIGN KEY ("cardId") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_cards" ADD CONSTRAINT "pack_cards_packId_products_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;