CREATE TYPE "public"."attribute" AS ENUM('DARK', 'DIVINE', 'EARTH', 'FIRE', 'LIGHT', 'WATER', 'WIND');--> statement-breakpoint
CREATE TYPE "public"."rarity" AS ENUM('COMMON', 'RARE', 'SUPER RARE', 'ULTRA RARE');--> statement-breakpoint
CREATE TABLE "cards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(60) NOT NULL,
	"price" integer NOT NULL,
	"image_url" varchar(255) NOT NULL,
	"attribute" "attribute" NOT NULL,
	"stock" integer DEFAULT 0 NOT NULL,
	"attack" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventories" (
	"user_name" varchar(30) NOT NULL,
	"card_id" integer NOT NULL,
	"creation_date" timestamp DEFAULT now() NOT NULL,
	"value" integer NOT NULL,
	CONSTRAINT "inventories_user_name_card_id_pk" PRIMARY KEY("user_name","card_id")
);
--> statement-breakpoint
CREATE TABLE "pack_cards" (
	"card_id" integer NOT NULL,
	"pack_id" integer NOT NULL,
	CONSTRAINT "pack_cards_card_id_pack_id_pk" PRIMARY KEY("card_id","pack_id")
);
--> statement-breakpoint
CREATE TABLE "packs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(60) NOT NULL,
	"price" integer NOT NULL,
	"image_url" varchar(255) NOT NULL,
	"rarity" "rarity" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"name" varchar(30) PRIMARY KEY NOT NULL,
	"password_hash" varchar(100) NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"yugi_pesos" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "inventories" ADD CONSTRAINT "inventories_user_name_users_name_fk" FOREIGN KEY ("user_name") REFERENCES "public"."users"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventories" ADD CONSTRAINT "inventories_card_id_cards_id_fk" FOREIGN KEY ("card_id") REFERENCES "public"."cards"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_cards" ADD CONSTRAINT "pack_cards_card_id_cards_id_fk" FOREIGN KEY ("card_id") REFERENCES "public"."cards"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_cards" ADD CONSTRAINT "pack_cards_pack_id_cards_id_fk" FOREIGN KEY ("pack_id") REFERENCES "public"."cards"("id") ON DELETE no action ON UPDATE no action;